# Generated by Django 4.1.7 on 2023-03-31 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Garagem', '0004_acessorios_cor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={},
        ),
    ]
